name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHA
        uses: actions/checkout@v2
      - name: Install modules
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:unit
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHA
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: 'tests/e2e/**/*'
        env:
          CYPRESS_baseUrl: http://localhost:8080/
